"""empty message

Revision ID: 1483badf433d
Revises: d6f58b3a57f3
Create Date: 2021-02-12 18:32:02.867987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1483badf433d'
down_revision = 'd6f58b3a57f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional', sa.Column('hashed_password', sa.String(length=20), nullable=False))
    op.drop_column('professional', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional', sa.Column('password', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('professional', 'hashed_password')
    # ### end Alembic commands ###
