"""empty message

Revision ID: 3eab95e5ec92
Revises: 1483badf433d
Create Date: 2021-02-13 09:02:38.165650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eab95e5ec92'
down_revision = '1483badf433d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional', sa.Column('salt', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional', 'salt')
    # ### end Alembic commands ###
