"""empty message

Revision ID: 606ed67b42af
Revises: 037ea49453c8
Create Date: 2021-02-16 15:34:58.666430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606ed67b42af'
down_revision = '037ea49453c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'client', 'professional', ['professional_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    # ### end Alembic commands ###
