"""empty message

Revision ID: a0a9a27e0a81
Revises: bae0f5b93917
Create Date: 2021-02-19 16:02:42.495120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0a9a27e0a81'
down_revision = 'bae0f5b93917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('UNIFAMILIAR', 'MULTIFAMILIAR', 'OFICINA', 'LOCAL_COMERCIAL', name='tipologies'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('project', 'notes',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'notes',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
    op.drop_table('tipology')
    # ### end Alembic commands ###
