"""empty message

Revision ID: bae0f5b93917
Revises: d5cacd5ce5b3
Create Date: 2021-02-18 19:58:29.887676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bae0f5b93917'
down_revision = 'd5cacd5ce5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('notes', sa.String(length=300), nullable=False))
    op.drop_column('project', 'final_notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('final_notes', mysql.VARCHAR(length=300), nullable=False))
    op.drop_column('project', 'notes')
    # ### end Alembic commands ###
