"""empty message

Revision ID: d651cd233936
Revises: 
Create Date: 2021-02-24 00:07:51.725070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd651cd233936'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesories_style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accesories_style_name', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=900), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_palette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_palette_name', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=900), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_style_name', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=900), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finishes_name', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=900), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('furniture_style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('furniture_style_name', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=900), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('profession', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('sketch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sketch_name', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=900), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texture_name', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=900), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tipology', sa.Enum('RESIDENCTIAL', 'OFFICE', 'COMERCIAL', name='tipologies'), nullable=False),
    sa.Column('project_name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('workspace', sa.Enum('LIVINGROOM', 'FAMILYROOM', 'KITCHEN', 'BATHROOM', 'BEDROOM', 'VESTIER', 'HOME_OFFICE', 'OFFICE', 'PLAYROOM', 'LAUNDRY', 'OUTDOOR', name='workspaces'), nullable=False),
    sa.Column('design_style_id', sa.Integer(), nullable=False),
    sa.Column('color_palette_id', sa.Integer(), nullable=False),
    sa.Column('sketch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_palette_id'], ['color_palette.id'], ),
    sa.ForeignKeyConstraint(['design_style_id'], ['design_style.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sketch_id'], ['sketch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_accesories_style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace', sa.Enum('LIVINGROOM', 'FAMILYROOM', 'KITCHEN', 'BATHROOM', 'BEDROOM', 'VESTIER', 'HOME_OFFICE', 'OFFICE', 'PLAYROOM', 'LAUNDRY', 'OUTDOOR', name='workspaces'), nullable=False),
    sa.Column('accesories_style_id', sa.Integer(), nullable=False),
    sa.Column('project_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accesories_style_id'], ['accesories_style.id'], ),
    sa.ForeignKeyConstraint(['project_data_id'], ['project_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_finishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace', sa.Enum('LIVINGROOM', 'FAMILYROOM', 'KITCHEN', 'BATHROOM', 'BEDROOM', 'VESTIER', 'HOME_OFFICE', 'OFFICE', 'PLAYROOM', 'LAUNDRY', 'OUTDOOR', name='workspaces'), nullable=False),
    sa.Column('finishes_id', sa.Integer(), nullable=False),
    sa.Column('project_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finishes_id'], ['finishes.id'], ),
    sa.ForeignKeyConstraint(['project_data_id'], ['project_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_furniture_style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace', sa.Enum('LIVINGROOM', 'FAMILYROOM', 'KITCHEN', 'BATHROOM', 'BEDROOM', 'VESTIER', 'HOME_OFFICE', 'OFFICE', 'PLAYROOM', 'LAUNDRY', 'OUTDOOR', name='workspaces'), nullable=False),
    sa.Column('furniture_style_id', sa.Integer(), nullable=False),
    sa.Column('project_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['furniture_style_id'], ['furniture_style.id'], ),
    sa.ForeignKeyConstraint(['project_data_id'], ['project_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_texture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace', sa.Enum('LIVINGROOM', 'FAMILYROOM', 'KITCHEN', 'BATHROOM', 'BEDROOM', 'VESTIER', 'HOME_OFFICE', 'OFFICE', 'PLAYROOM', 'LAUNDRY', 'OUTDOOR', name='workspaces'), nullable=False),
    sa.Column('texture_id', sa.Integer(), nullable=False),
    sa.Column('project_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_data_id'], ['project_data.id'], ),
    sa.ForeignKeyConstraint(['texture_id'], ['texture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_texture')
    op.drop_table('project_furniture_style')
    op.drop_table('project_finishes')
    op.drop_table('project_accesories_style')
    op.drop_table('project_data')
    op.drop_table('project')
    op.drop_table('client')
    op.drop_table('texture')
    op.drop_table('sketch')
    op.drop_table('professional')
    op.drop_table('furniture_style')
    op.drop_table('finishes')
    op.drop_table('design_style')
    op.drop_table('color_palette')
    op.drop_table('accesories_style')
    # ### end Alembic commands ###
